LOCAL_PORT=XXXXX
LOCAL_DIR_DB_DATA='XXXXX'
MYSQL_ROOT_PASSWORD='XXXXX'
docker run --name test-mysql -d -p $LOCAL_PORT:3306 -e MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD -v $LOCAL_DIR_DB_DATA:/var/lib/mysql mysql